# @package _global_
optimizer_id: HPI-ParEGO-50-quantile
optimizer_container_id: SMAC3
optimizer:
  smac_cfg:
    scenario:
        output_directory: ${outdir}
        name: smac3output
    smac_kwargs:
      acquisition_maximizer:
        _target_: hpi_parego.my_local_and_random_search_configspace.MyLocalAndSortedRandomSearchConfigSpace
        _partial_: true
        path_to_run: ${optimizer.smac_cfg.scenario.output_directory}/${optimizer.smac_cfg.scenario.name}/${optimizer.smac_cfg.scenario.seed}
        adjust_cs: true
        hpi_method: hypershap
        constant: true
        adjust_previous_cfgs: false
        set_to_default: true   
        thresh: 0.5
        dynamic_decay: linear # or linear 
        adjust_cs_method: default # or random
        thresh_list: [0.9,0.8,0.7,0.6,0.5,0.4,0.3]
        n_trials: ${optimizer.smac_cfg.scenario.n_trials}   
      acquisition_function:
        _target_: hpi_parego.my_ei_hpi.MyEI
      config_selector:
        _target_: hpi_parego.my_config_selector.MyConfigSelector
        _partial_: true