# @package _global_
optimizer_id: HPI-ParEGO-50-quantile
optimizer_container_id: SMAC3
optimizer:
  smac_cfg:
    scenario:
        output_directory: ${outdir}
        name: smac3output
    smac_kwargs:
      acquisition_maximizer:
        _target_: hpi_parego.my_local_and_random_search_configspace.MyLocalAndSortedRandomSearchConfigSpace
        _partial_: true
        path_to_run: ${optimizer.smac_cfg.scenario.output_directory}/${optimizer.smac_cfg.scenario.name}/${optimizer.smac_cfg.scenario.seed}
        adjust_cs: default #'default', 'random', 'incumbent', 'no'
        hpi_method: fanova
        adjust_previous_cfgs: no #'true_no_retrain', 'no', 'true_retrain'
        rnd_aug_pc: false # random augmentation of previous configs  
        thresh: 0.5 # [0.0,0.2,0.4,0.6,0.8,0.0]
        cs_proba_hpi: false
        n_trials: ${optimizer.smac_cfg.scenario.n_trials}   
        gt_hpi: false
      acquisition_function:
        _target_: hpi_parego.my_ei_hpi.MyEI
      config_selector:
        _target_: hpi_parego.my_config_selector.MyConfigSelector
        _partial_: true